server:
  port: 8080

jwt:
  secret: "jwt_secret"

database:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "companydb"
  sslmode: "disable"

kafka:
  brokers:
    - "kafka:9092"
  topic: "company-events"
